<?xml version="1.0" encoding="utf-8"?><Database Name="DB" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\DB.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Notatki.Properties.Settings" SettingsPropertyName="DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Page" Member="Pages">
    <Type Name="Page">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Page_Shape" Member="Shapes" ThisKey="Id" OtherKey="PageId" Type="Shape" />
    </Type>
  </Table>
  <Table Name="dbo.Shape" Member="Shapes">
    <Type Name="Shape">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Color" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Shape_Point" Member="Points" ThisKey="Id" OtherKey="ShapeId" Type="Point" />
      <Association Name="Page_Shape" Member="Page" ThisKey="PageId" OtherKey="Id" Type="Page" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Point" Member="Points">
    <Type Name="Point">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="X" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Y" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShapeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Shape_Point" Member="Shape" ThisKey="ShapeId" OtherKey="Id" Type="Shape" IsForeignKey="true" />
    </Type>
  </Table>
</Database>